using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;

public class AddressableEnumGenerator
{
    private const string _directory = "Assets/02. Scripts/02-01. Common/Enum";
    private const string _addressableEnumFilePath = _directory + "/EAddressables.cs";

    [MenuItem("Tools/Generate Addressable Enum")]
    public static void GenerateAddressableEnum()
    {
        if (!Directory.Exists(_directory))
        {
            Directory.CreateDirectory(_directory);
        }

        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
        {
            UnityEngine.Debug.LogError("AddressableAssetSettings not found.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by AddressableEnumGenerator");
        sb.AppendLine("public enum EAddressables");
        sb.AppendLine("{");

        foreach (var group in settings.groups)
        {
            if (group == null || group.entries == null) continue;

            foreach (var entry in group.entries)
            {
                if (string.IsNullOrEmpty(entry.address))
                    continue;

                string enumKey = MakeEnumName(entry.address);
                sb.AppendLine($"    {enumKey},");
            }
        }

        sb.AppendLine("}");

        File.WriteAllText(_addressableEnumFilePath, sb.ToString());
        AssetDatabase.Refresh();

        UnityEngine.Debug.Log($"Addressable enum generated at {_addressableEnumFilePath}");
    }

    private static string MakeEnumName(string addressableKey)
    {
        if (string.IsNullOrWhiteSpace(addressableKey))
        {
            throw new ArgumentException("키가 비어있거나 공백입니다.");
        }
        if (char.IsDigit(addressableKey[0]))
        {
            throw new ArgumentException("키는 숫자로 시작할 수 없습니다: " + addressableKey);
        }
        foreach (char c in addressableKey)
        {
            if (!(char.IsLetterOrDigit(c) || c == '_'))
            {
                throw new ArgumentException($"키에 유효하지 않은 문자가 포함되어 있습니다: '{c}' in \"{addressableKey}\"");
            }
        }
        return addressableKey;
    }
}
