using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;

public class AddressableEnumGenerator
{
    private const string _directory = "Assets/02. Scripts/02-01. Common/Enum";
    private const string _addressableEnumFilePath = _directory + "/EAddressables.cs";

    [MenuItem("Tools/Generate Addressable Enum")]
    public static void GenerateAddressableEnum()
    {
        if (!Directory.Exists(_directory))
        {
            Directory.CreateDirectory(_directory);
        }

        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
        {
            UnityEngine.Debug.LogError("AddressableAssetSettings not found.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by AddressableEnumGenerator");
        sb.AppendLine("public enum EAddressables");
        sb.AppendLine("{");

        foreach (var group in settings.groups)
        {
            if (group == null || group.entries == null) continue;

            foreach (var entry in group.entries)
            {
                if (string.IsNullOrEmpty(entry.address))
                    continue;

                string enumKey = MakeEnumName(entry.address);
                sb.AppendLine($"    {enumKey},");
            }
        }

        sb.AppendLine("}");

        File.WriteAllText(_addressableEnumFilePath, sb.ToString());
        AssetDatabase.Refresh();

        UnityEngine.Debug.Log($"Addressable enum generated at {_addressableEnumFilePath}");
    }

    private static string MakeEnumName(string address)
    {
        // 공백은 _로, 영숫자와 _만 남기고 제거, 숫자 시작 시 _ 붙임
        var cleaned = address.Replace(" ", "_");
        StringBuilder builder = new StringBuilder();
        foreach (var c in cleaned)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                builder.Append(c);
        }

        if (builder.Length == 0)
            return "_EmptyAddress";

        if (char.IsDigit(builder[0]))
            builder.Insert(0, '_');

        return builder.ToString();
    }
}
