using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using System.Collections.Generic;

public class AddressableEnumGenerator
{
    private const string _directory = "Assets/02. Scripts/02-01. Common/Enum";
    private const string _keyEnumFilePath = _directory + "/EAddressableKeys.cs";
    private const string _labelEnumFilePath = _directory + "/EAddressableLabels.cs";

    [MenuItem("Tools/Generate Addressable Enums")]
    public static void GenerateAddressableEnums()
    {
        if (!Directory.Exists(_directory))
            Directory.CreateDirectory(_directory);

        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
        {
            UnityEngine.Debug.LogError("AddressableAssetSettings not found.");
            return;
        }

        var keyBuilder = new StringBuilder();
        keyBuilder.AppendLine("// Auto-generated by AddressableEnumGenerator");
        keyBuilder.AppendLine("public enum EAddressableKeys");
        keyBuilder.AppendLine("{");

        var labelBuilder = new StringBuilder();
        labelBuilder.AppendLine("// Auto-generated by AddressableEnumGenerator");
        labelBuilder.AppendLine("public enum EAddressableLabels");
        labelBuilder.AppendLine("{");

        HashSet<string> usedKeyNames = new HashSet<string>();
        HashSet<string> usedLabelNames = new HashSet<string>();

        // Addressable Keys
        foreach (var group in settings.groups)
        {
            if (group == null || group.entries == null)
                continue;

            foreach (var entry in group.entries)
            {
                if (string.IsNullOrEmpty(entry.address))
                    continue;

                try
                {
                    string enumName = MakeEnumName(entry.address);
                    if (usedKeyNames.Add(enumName))
                        keyBuilder.AppendLine($"    {enumName},");
                }
                catch (ArgumentException e)
                {
                    UnityEngine.Debug.LogWarning($"주소 '{entry.address}' 무시됨: {e.Message}");
                }
            }
        }

        // Labels
        foreach (var label in settings.GetLabels())
        {
            if (string.IsNullOrWhiteSpace(label))
                continue;

            try
            {
                string enumName = MakeEnumName(label);
                if (usedLabelNames.Add(enumName))
                    labelBuilder.AppendLine($"    {enumName},");
            }
            catch (ArgumentException e)
            {
                UnityEngine.Debug.LogWarning($"라벨 '{label}' 무시됨: {e.Message}");
            }
        }

        keyBuilder.AppendLine("}");
        labelBuilder.AppendLine("}");

        File.WriteAllText(_keyEnumFilePath, keyBuilder.ToString());
        File.WriteAllText(_labelEnumFilePath, labelBuilder.ToString());

        AssetDatabase.Refresh();

        UnityEngine.Debug.Log($"Addressable Key Enum 생성 완료: {_keyEnumFilePath}");
        UnityEngine.Debug.Log($"Addressable Label Enum 생성 완료: {_labelEnumFilePath}");
    }

    private static string MakeEnumName(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            throw new ArgumentException("키가 비어있거나 공백입니다.");

        var cleaned = raw.Replace(" ", "_");

        StringBuilder builder = new StringBuilder();
        foreach (var c in cleaned)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                builder.Append(c);
        }

        if (builder.Length == 0)
            throw new ArgumentException("유효한 문자가 없습니다: " + raw);

        if (char.IsDigit(builder[0]))
            builder.Insert(0, '_');

        return builder.ToString();
    }
}
