using System.IO;
using UnityEditor;
using UnityEngine;

public class LayerEnumGenerator : MonoBehaviour
{
    private const string _directory = "Assets/00. Main/02. Scripts/02-01. Common/Enum";
    private const string _layerEnumFilePath = _directory + "/ELayers.cs";

    [MenuItem("Tools/Generate Layer Enum")]
    public static void GenerateLayerEnum()
    {
        if (!Directory.Exists(_directory))
        {
            Directory.CreateDirectory(_directory);
        }

        using (StreamWriter writer = new StreamWriter(_layerEnumFilePath))
        {
            writer.WriteLine("// Auto-generated by LayerEnumGenerator");
            writer.WriteLine("public enum ELayers");
            writer.WriteLine("{");

            for (int i = 0; i < 32; i++)
            {
                string layerName = LayerMask.LayerToName(i);
                if (!string.IsNullOrEmpty(layerName))
                {
                    writer.WriteLine($"{layerName.Replace(" ", "_")} = {i},");
                }
            }

            writer.WriteLine("}");
        }

        AssetDatabase.Refresh();
    }
}
