// Auto-generated by AddressableEnumGenerator
public enum EAddressableKeys
{
    Prefab_Machine,
    Prefab_Output_Base,
    Prefab_Ingredient_Base,
    Prefab_Player,
    Prefab_Potion_Base,
    Prefab_Furniture,
    Prefab_CustomerNPC,
    Prefab_Storage,
}
