// Auto-generated by AddressableEnumGenerator
public enum EAddressableKeys
{
    Prefab_Machine,
    Prefab_Ingredient_10000,
    Prefab_AddressableTest1,
    Prefab_Player,
    Prefab_AddressableTest2,
    Prefab_Furniture,
    Prefab_CustomerNPC,
    Prefab_Storage,
}
