// Auto-generated by AddressableEnumGenerator
public enum EAddressableKeys
{
    Prefab_Structure_10018,
    Prefab_Structure_10000,
    Prefab_Output_Base,
    Prefab_Ingredient_Base,
    Prefab_Player,
    Prefab_Potion_Base,
    Prefab_CustomerNPC,
}
