// Auto-generated by SceneEnumGenerator
public enum ESceneNames
{
    LSJ_MirrorTest,
    RoomTestScene,
    LSJ_PrototypeScene,
    CMG_PrototypeScene,
    KYS_PrototypeScene,
    WYP_PrototypeScene,
    SHJ_PrototypeScene,
}
