// Auto-generated by TagEnumGenerator
public enum ETags
{
Untagged,
Respawn,
Finish,
EditorOnly,
MainCamera,
Player,
GameController,
EditorGeneratedWalls,
Layout,
Potion,
Missile,
Target,
GridVisualization,
Grid,
PreviewSystem,
}
